server:
  port: 9010
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2b8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: auth-server
eureka:
  client:
    service-url:
      defaultZone:  http://admin:123456@server1:9000/eureka/,http://admin:123456@server2:9001/eureka/
  instance:
    prefer-ip-address: true
