server:
  port: 9003
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:123456@server1:9000/eureka/,http://admin:123456@server2:9001/eureka/
spring:
  application:
    name: my-user-provider