spring:
  security: # 配置安全验证
    user:
      name: admin
      password: 123456
  application:
    name: server2
eureka:
  instance:
    hostname: server2
  client:
    service-url:
      defaultZone: http://admin:123456@server1:9000/eureka/
server:
  port: 9001